# Generated by Django 4.2 on 2023-04-04 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officers', '0002_officer_address_officer_dni_officer_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officer',
            name='address',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='officer',
            name='dni',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='officer',
            name='phone',
            field=models.CharField(max_length=50),
        ),
    ]
