# Generated by Django 4.2 on 2023-04-04 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('idAgency', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=20)),
                ('cp', models.CharField(max_length=10)),
            ],
        ),
    ]
