# Generated by Django 4.2 on 2023-04-04 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('officers', '0003_alter_officer_address_alter_officer_dni_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Citation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('violationDate', models.DateField()),
                ('violationTime', models.TimeField()),
                ('route', models.CharField(max_length=20)),
                ('county', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('oln', models.CharField(max_length=10)),
                ('oln_number', models.CharField(max_length=10)),
                ('license_class', models.CharField(max_length=10)),
                ('cdl', models.BooleanField()),
                ('name', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=10)),
                ('hair_color', models.CharField(max_length=10, null=True)),
                ('eye_color', models.CharField(max_length=10, null=True)),
                ('height', models.CharField(max_length=8)),
                ('address', models.CharField(max_length=50)),
                ('city_passenger', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=10)),
                ('zip_code', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=40)),
                ('vin', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=20)),
                ('year', models.IntegerField()),
                ('make', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('crash', models.BooleanField()),
                ('passengers', models.BooleanField()),
                ('spanish_speaker', models.BooleanField()),
                ('in_car_video', models.BooleanField()),
                ('body_camera', models.BooleanField()),
                ('school_zone', models.BooleanField()),
                ('construction_zone', models.BooleanField()),
                ('workers_present', models.BooleanField()),
                ('violations', models.CharField(max_length=100)),
                ('officer_note', models.CharField(max_length=100, null=True)),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='officers.officer')),
            ],
        ),
    ]
