# Generated by Django 4.2 on 2023-04-04 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citation',
            name='eye_color',
            field=models.CharField(default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='citation',
            name='hair_color',
            field=models.CharField(default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='citation',
            name='officer_note',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
